[package]
name = "gitflow-demo"
version = "1.0.0"
authors = ["Jimmy Yip <jimmy.yip@crypto.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
